SEGMENTS = [
    {
        "id": "01",
        "title": "开场问题",
        "subtitle": "一句话里的每个词，怎么知道自己真正的意思？这就是 Attention 要解决的问题。",
        "duration": 6.0,
    },
    {
        "id": "02",
        "title": "同一个词，不同上下文",
        "subtitle": "比如“苹果”这个词，单独看可能是水果；放到“苹果 手机 很 快”里，它更像是在说品牌。",
        "duration": 8.5,
    },
    {
        "id": "03",
        "title": "朴素想法",
        "subtitle": "如果一个词只看自己，它就会迷路；如果它能看看周围的词，意思就会被上下文校准。",
        "duration": 7.5,
    },
    {
        "id": "04",
        "title": "核心直觉",
        "subtitle": "Self-Attention 的直觉是：每个词都向整句话发问，找出哪些词最值得参考。",
        "duration": 7.0,
    },
    {
        "id": "05",
        "title": "Q K V",
        "subtitle": "Query 是“我想找什么线索”；Key 是“我能提供什么线索”；Value 是“真正要传过去的信息”。",
        "duration": 9.0,
    },
    {
        "id": "06",
        "title": "匹配",
        "subtitle": "“苹果”发出一个 Query：“我该怎么理解？”每个词拿出自己的 Key，和它做一次匹配打分。",
        "duration": 8.0,
    },
    {
        "id": "07",
        "title": "注意力权重",
        "subtitle": "分数越高，说明这个词越有用。Softmax 会把分数变成一组加起来等于 1 的权重。",
        "duration": 8.0,
    },
    {
        "id": "08",
        "title": "传递信息",
        "subtitle": "然后用这些权重去加权 Value：手机的权重大，就把“品牌、设备”的信息更多传给苹果。",
        "duration": 8.5,
    },
    {
        "id": "09",
        "title": "上下文化表示",
        "subtitle": "于是原来模糊的“苹果”向量，被更新成“苹果手机”语境下的表示。",
        "duration": 7.0,
    },
    {
        "id": "10",
        "title": "公式出现",
        "subtitle": "公式 Attention(Q,K,V)=softmax(QK^T/sqrt(d_k))V，其实就是：匹配、归一化、加权求和。",
        "duration": 9.5,
    },
    {
        "id": "11",
        "title": "多头注意力",
        "subtitle": "一个头可以看品牌关系，另一个头可以看修饰关系。多头注意力就是让模型同时学多种看法。",
        "duration": 8.5,
    },
    {
        "id": "12",
        "title": "遮罩",
        "subtitle": "在 GPT 这类模型里，预测下一个词时不能偷看未来，所以会用 Mask 把未来位置挡住。",
        "duration": 8.0,
    },
    {
        "id": "13",
        "title": "三句总结",
        "subtitle": "记住三件事：Attention 找相关词；Value 传递信息；多头让模型从多个角度理解上下文。",
        "duration": 8.0,
    },
]
